### ISSUE TITLE
クローラー修正・拡張プロパティ

### ISSUE THREAD

**Issue by altus5-itako** [altus5-itako/itako-task-project#53]
拡張プロパティを収集する。

- 大分類・中分類・小分類
- 保存期間満了日

**Comment by altus5-itako** [comment]
拡張プロパティ名を定義ファイルに保持
```
# ファイル詳細の属性(英字の値の大文字小文字は厳密に)
# ESのインデックスattachmentの項目(Contentは除く)
attachment:
  title: "title"
  contentType: "Content-Type"
# ESのインデックスfile_costumの項目
fileCustom:
  classLarge: "custom:大分類"
  classMedium: "custom:中分類"
  classSmall: "custom:小分類"
  periodExpirationDate: "custom:保存期間満了日"
```
これを利用する
